In [1]:
import numpy as np

In [3]:
req_q1 = np.array([10,12,9])
req_q1.ndim


1

In [6]:
rev = np.array([[10,12,9], 
                [12,23,3]])
rev.ndim

2

In [8]:
rev[1,1]

np.int64(23)

In [23]:
revf = np.array([[10,12,9], 
                [12,23,5]], dtype=np.float64)

np.sort(revf, axis=None)

array([ 5.,  9., 10., 12., 12., 23.])

In [25]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [35]:
np.linspace(4.99,5,7)

array([4.99      , 4.99166667, 4.99333333, 4.995     , 4.99666667,
       4.99833333, 5.        ])

In [55]:
r1 = np.array(
    [[2, 3, 4, 5],
     [4, 3, 4, 5],
     [4, 3, 4, 5],
     [4, 3, 4, 5]],
    ndmin=3
)
r2 = np.array([[2,3,4], [4,3,4]])

f2 = r1.flatten()
f1 = r2.ravel()

print(r1)
print(r2)
print(f1)
print(f2)

r1.shape

[[[2 3 4 5]
  [4 3 4 5]
  [4 3 4 5]
  [4 3 4 5]]]
[[2 3 4]
 [4 3 4]]
[2 3 4 4 3 4]
[2 3 4 5 4 3 4 5 4 3 4 5 4 3 4 5]


(1, 4, 4)

In [53]:
r1.sum(axis=2)

array([[14, 16, 16, 16]])